const highConfidence = [
  "Nailed it harder than a senior dev explaining Git rebasing.",
  "More confident than a junior dev pushing to production on Friday.",
  "Accuracy level: Perfectly balanced, like all things should be.",
  "This analysis is more solid than your project's dependency tree.",
  "More dependable than your plants' will to live.",
  "More reliable than your neighbor's Wi-Fi.",
  "Results clearer than commented code. Yes, that exists.",
  "This analysis is more secure than your SSH keys (which we all know is 'password123').",
  "Precision level: Makes quantum computing look like a pocket calculator.",
  "More organized than your 27,394 npm packages.",
  "More certain than your understanding of blockchain.",
  "More consistent than your code style without Prettier.",
  "More precise than a cat walking across your keyboard and accidentally fixing a bug.",
  "More thorough than your mom checking your browser history.",
  "More dependable than your backup backup backup drive.",
  "Confidence higher than a tech recruiter's LinkedIn enthusiasm.",
  "Confidence level: Makes Gandalf's 'You shall not pass!' look uncertain.",
  "More stable than your relationship with Stack Overflow.",
  "More reliable than your plant-watering schedule.",
  "More precise than an elf's arrow in Lord of the Rings.",
  "More meticulous than a Vulcan's emotional control.",
  "More certain than a conspiracy theorist's 'research'.",
  "More accurate than your 'five minutes more' morning alarm.",
  "More specific than a D&D dungeon master's 30-sided die.",
  "Precision that would make Heisenberg uncertain about his uncertainty.",
];