const lowConfidence = [
  "This pattern is about as predictable as JavaScript equality.",
  "I'm as confused as a CSS developer in a backend meeting.",
  "These results are more mysterious than Python's whitespace rules.",
  "Confidence level: Stack overflow copypasta.",
  "Understanding level: README.md without documentation.",
  "Trust level: Like using == instead of ===",
  "About as reliable as a Windows update.",
  "Accuracy comparable to first-time regex writing.",
  "As trustworthy as a npm install with 1247 vulnerabilities.",
  "Confidence rating: Like deploying to production without testing.",
  "Accuracy level: HTML written by AI. Wait, what's a <div>?",
  "Stability rating: WordPress plugin from 2009. No updates.",
  "Trust rating: Using 'password123' as API key. It's fine.",
  "As stable as a Jenga tower in an earthquake.",
  "Trust level: Like letting AI control nuclear reactors.",
  "Accuracy: Machine learning on dataset of one. Skynet is just a playlist, right?",
  "As accurate as dads trying to find items in grocery store.",
  "Accuracy: Magic 8-Ball debugging. 'Outlook: hazy'",
  "Accuracy: Magic 8-Ball level precision. 'Concentrate and ask again'",
  "Dependability: Magic 8-Ball quantum predictions. 'As I see it, yes'",
  "Trust level: 'I have read the terms & conditions'.",
  "Precision Level: Using sundials as your primary speed test'",
  "Confidence: Ouija board code reviews. How insane am I? Ouiji board?",
  "Trust rating: Quantum computing on a calculator watch.",
];
