const progress = [
  "Still working. Unlike your keyboard's Caps Lock indicator.",
  "Processing... Like your browser tabs, but actually doing something.",
  "Making progress! Almost as fast as Windows updates.",
  "Computing things. Please entertain yourself by counting to 1 in binary.",
  "If this analysis were any more thorough, it'd need its own LinkedIn profile.",
  "Still here, still calculating, still judging your code formatting.",
  "Working harder than a GPU in a crypto mining rig.",
  "Analyzing patterns faster than developers abandon side projects.",
  "Processing at the speed of `npm install`. Just kidding, much faster.",
  "Running at quantum speed. Or maybe your internet is just slow.",
  "Processing data like a caffeinated squirrel on a sugar rush.",
  "Computing at the speed of light, minus traffic delays.",
  "Processing at the speed of your last-minute deadline panic.",
  "Working harder than your smart fridge trying to connect to WiFi.",
  "Loading... Like my PhD in procrastination studies.",
  "Processing at the rate of medieval carrier pigeons with jet packs.",
  "Still here, like that mysterious USB cable that fits nothing.",
  "Working like a Netflix algorithm trying to understand your taste.",
  "Computing at the speed of explaining why Pluto isn't a planet anymore.",
  "Processing at the pace of your parents trying to FaceTime.",
  "Analyzing with the precision of a stormtrooper in a sharpshooting contest.",
];